package com.hedvig.backoffice.services.account;

public enum ChargeStatus {
  INITIATED,
  WAITING_FOR_SUBSCRIPTION,
  SCHEDULING_SUBSCRIPTION,
  SCHEDULE_SUBSCRIPTION_FAILED,
  SUBSCRIPTION_SCHEDULED_AND_WAITING_FOR_APPROVAL,
  APPROVED_FOR_CHARGE,
  SCHEDULING_CHARGE,
  CHARGE_REQUESTING,
  CHARGE_REQUEST_FAILED,
  CHARGE_INITIATED,
  CHARGE_FAILED,
  CHARGE_COMPLETED,
}
