server:
  port: 8443
  httpPort: 8080
  session:
    cookie:
      max-age: 3600
      http-only: true
      secure: true
  servlet:
    session:
      timeout: 7200s

logging:
  level:
    com:
      hedvig: DEBUG

  http:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  cloud:
    config:
      allow-override: false

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

intervals:
  chat: 1000

gatekeeper:
  baseUrl: https://id.dev.hedvigit.com

graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    corsEnabled: false

graphiql:
  mapping: /graphiql
  endpoint: /api/graphql
  enabled: true
  pageTitle: BackOffice GraphiQL

spring:
  application:
    name: back-office
  jackson:
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

cloud:
  aws:
    credentials.useDefaultAwsCredentialsChain: true

---

spring:
    profiles: development, test

# Upstream services

botservice:
    baseUrl: http://localhost:4081
    questionId: main.question
    mode: auto-discover

memberservice:
    baseUrl: http://localhost:4084
    mode: auto-discover

claims:
    baseUrl: http://localhost:4083
    mode: auto-discover

productPricing:
    baseUrl: http://localhost:4085
    mode: auto-discover

underwriter:
    baseUrl: http://localhost:5698
    mode: auto-discover

paymentService:
    baseUrl: http://localhost:8086
    mode: auto-discover

meerkat:
    baseUrl: http://localhost:4123
    mode: stub # does not have a health endpoint

accountService:
    baseUrl: http://localhost:8090
    mode: auto-discover

priceEngine:
    baseUrl: http://localhost:5699
    mode: auto-discover

itemizer:
    baseUrl: http://localhost:5700
    mode: auto-discover

apiGateway:
    baseUrl: http://localhost:8080
    mode: auto-discover
    token: blah
