security:
  basic:
    enabled: true
    authorize-mode: NONE

tracker:
  stub: true

botservice:
  stub: true

userservice:
  stub: true

jwt:
  enabled: true

cors:
  origins: http://localhost:9000
  methods: GET, POST, PUT, DELETE
