security:
  basic:
    enabled: true
    authorize-mode: NONE

tracker:
  stub: true

botservice:
  questionId: mock.id
  stub: true

memberservice:
  stub: true

claims:
  stub: true

expo:
  stub: true

cors:
  origins: http://localhost:9000
  methods: GET, POST, PUT, DELETE

spring:
  datasource:
    url: jdbc:h2:mem:~/memorydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
