security:
  basic:
    enabled: true
    authorize-mode: NONE

tracker:
  stub: true

botservice:
  questionId: mock.id
  stub: true

memberservice:
  stub: true

claims:
  stub: true

expo:
  stub: true

productPricing:
  stub: true

oauth:
  enabled: false
  enableHttps: false
  google:
    client:
      clientId: 509635501238-mghmadmqrsbgk89hd38op6d6f1e3ct7q.apps.googleusercontent.com
      clientSecret: xZDZBPMcLxvbuDYo6hfEHhkG
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile, email

spring:
  datasource:
    url: jdbc:h2:mem:~/memorydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
