server:
  port: 8443
  httpPort: 8080
  overHttps: true

logging:
  level:
    com:
      hedvig: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/back-office
    username: postgres
    password: iambatman
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver

  http:
      multipart:
        max-file-size: 512MB
        max-request-size: 512MB
  cloud:
    config:
      allow-override: false

  profiles:
    active: development

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

intervals:
  tracker: 5000
  chat: 1000
  claims: 5000

websocket:
  max-sile-size: 5242880

tracker:
  baseUrl: http://localhost:4082
  urls:
    assets: /assets
    update: /asset
  stub: false

botservice:
  baseUrl: http://localhost:4081
  questionId: main.question
  stub: false

memberservice:
  baseUrl: http://localhost:4084
  urls:
    search: /i/member/search
    getById: /member
  stub: false

claims:
  baseUrl: http://localhost:4083
  stub: false

productPricing:
  baseUrl: http://localhost:4085
  stub: false

oauth:
  enabled: true
  hds: hedvig.com
  baseUrl: https://backoffice.dev.hedvigit.com
  google:
    client:
      clientId:
      clientSecret:
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile, email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me

cors:
  origins:
  methods: