package com.hedvig.backoffice.services.account.dto

enum class AccountEntryType {
  CORRECTION,
  SUBSCRIPTION,
  CAMPAIGN,
  PAYOUT,
  CHARGE,
  REFERRAL_DISCOUNT,
  FREE_MONTH_DISCOUNT,
  PERCENTAGE_DISCOUNT,
  BUNDLE_DISCOUNT_COST_DEDUCTION,
  BUNDLE_DISCOUNT_PERCENTAGE_DEDUCTION,
  LOSS
}
