package com.hedvig.backoffice.graphql.types;

public enum ClaimTypes {
  TheftClaim,
  AccidentalDamageClaim,
  AssaultClaim,
  WaterDamageClaim,
  TravelAccidentClaim,
  LuggageDelayClaim,
  NotCoveredClaim,
  FireDamageClaim,
  ApplianceClaim,
  ConfirmedFraudClaim,
  LiabilityClaim,
  LegalProtectionClaim,
  WaterDamageBathroomClaim,
  WaterDamageKitchenClaim,
  BurglaryClaim,
  FloodingClaim,
  EarthquakeClaim,
  InstallationsClaim,
  SnowPressureClaim,
  StormDamageClaim,
  VerminAndPestsClaim,
  TestClaim,
}
