apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: back-office-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: back-office-service
    spec:
      containers:
      - name: back-office-service
        image: 201427539538.dkr.ecr.eu-central-1.amazonaws.com/back-office:11
        ports:
        - containerPort: 8080
          protocol: TCP
