// TODO add all action types
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_EXISTING = 'LOGIN_EXISTING';
export const LOGOUT = 'LOGOUT';

export const ASSET_UPDATING = 'ASSET_UPDATING';
export const ASSET_UPDATE_SUCCESS = 'ASSET_UPDATE_SUCCESS';
export const ASSET_UPDATE_ERROR = 'ASSET_UPDATE_ERROR';
export const ASSET_REQUESTING = 'ASSET_REQUESTING';
export const ASSET_REQUEST_SUCCESS = 'ASSET_REQUEST_SUCCESS';
export const ASSET_REQUEST_ERROR = 'ASSET_REQUEST_ERROR';

export const CLIENT_SET = 'CLIENT_SET';
export const CLIENT_UNSET = 'CLIENT_UNSET';

export const POLL_START = 'POLL_START';
export const POLL_STOP = 'POLL_STOP';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';