export const ASSET_UPDATING = 'ASSET_UPDATING';
export const ASSET_UPDATE_SUCCESS = 'ASSET_UPDATE_SUCCESS';
export const ASSET_UPDATE_ERROR = 'ASSET_UPDATE_ERROR';
export const ASSET_REQUESTING = 'ASSET_REQUESTING';
export const ASSET_REQUEST_SUCCESS = 'ASSET_REQUEST_SUCCESS';
export const ASSET_REQUEST_ERROR = 'ASSET_REQUEST_ERROR';

export const POLL_START = 'POLL_START';
export const POLL_STOP = 'POLL_STOP';
