export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const ERROR_RECEIVED = 'ERROR_RECEIVED';
export const CLEAR_MESSAGES_LIST = 'CLEAR_MESSAGES_LIST';
export const SET_ACTIVE_CONNECTION = 'SET_ACTIVE_CONNECTION';

export const USER_REQUESTING = 'USER_REQUESTING';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR';

export const USERS_REQUESTING = 'USERS_REQUESTING';
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS';
export const USERS_ERROR = 'USERS_ERROR';

export const USER_SEARCH_REQUESTING = 'USER_SEARCH_REQUESTING';
export const USERS_SEARCH_SUCCESS = 'USERS_SEARCH_SUCCESS';

export const NEW_MESSAGES_RECEIVED = 'NEW_MESSAGES_RECEIVED';

export const SET_USER_FILTER = 'SET_USER_FILTER';

export const INSURANCE_REQUESTING = 'INSURANCE_REQUESTING';
export const INSURANCE_REQUEST_SUCCESS = 'INSURANCE_REQUEST_SUCCESS';
export const INSURANCE_ERROR = 'INSURANCE_ERROR';

export const SAVE_INSURANCE_DATE = 'SAVE_INSURANCE_DATE';
export const SAVE_DATE_SUCCESS = 'SAVE_DATE_SUCCESS';

export const SORT_USERS_LIST = 'SORT_USERS_LIST';
