export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const ERROR_RECEIVED = 'ERROR_RECEIVED';
export const CLEAR_MESSAGES_LIST = 'CLEAR_MESSAGES_LIST';
export const SET_ACTIVE_CONNECTION = 'SET_ACTIVE_CONNECTION';

export const USER_REQUESTING = 'USER_REQUESTING';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR';

export const USERS_REQUESTING = 'USERS_REQUESTING';
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS';
export const USERS_REQUEST_ERROR = 'USERS_REQUEST_ERROR';

export const USER_SEARCH_REQUESTING = 'USER_SEARCH_REQUESTING';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_ERROR = 'USER_SEARCH_ERROR';

export const NEW_MESSAGES_RECEIVED = 'NEW_MESSAGES_RECEIVED';
