export const CLAIM_REQUESTING = 'CLAIM_REQUESTING';
export const CLAIM_REQUEST_SUCCESS = 'CLAIM_REQUEST_SUCCESS';
export const CLAIM_REQUEST_ERROR = 'CLAIM_REQUEST_ERROR';

export const CLAIM_UPDATING = 'CLAIM_UPDATING';
export const CLAIM_UPDATE_SUCCESS = 'CLAIM_UPDATE_SUCCESS';
export const CLAIM_UPDATE_ERROR = 'CLAIM_UPDATE_ERROR';

export const CLAIM_CREATING = 'CLAIM_CREATING';
export const CLAIM_CREATE_SUCCESS = 'CLAIM_CREATE_SUCCESS';
export const CLAIM_CREATE_ERROR = 'CLAIM_CREATE_ERROR';
