export const CLAIMS_REQUESTING = 'CLAIMS_REQUESTING';
export const CLAIMS_REQUEST_SUCCESS = 'CLAIMS_REQUEST_SUCCESS';
export const CLAIMS_REQUEST_ERROR = 'CLAIMS_REQUEST_ERROR';

export const CLAIM_UPDATING = 'CLAIM_UPDATING';
export const CLAIM_UPDATE_SUCCESS = 'CLAIM_UPDATE_SUCCESS';
export const CLAIM_UPDATE_ERROR = 'CLAIM_UPDATE_ERROR';

export const CLAIM_TYPES = 'CLAIM_TYPES';
export const CLAIM_TYPES_SUCCESS = 'CLAIM_TYPES_SUCCESS';
export const CLAIM_TYPES_ERROR = 'CLAIM_TYPES_ERROR';

export const CLAIM_CREATING = 'CLAIM_CREATING';
export const CLAIM_CREATE_SUCCESS = 'CLAIM_CREATE_SUCCESS';
export const CLAIM_CREATE_ERROR = 'CLAIM_CREATE_ERROR';

export const CLAIM_REQUESTING = 'CLAIM_REQUESTING';
export const CLAIM_REQUEST_SUCCESS = 'CLAIM_REQUEST_SUCCESS';
export const CLAIM_REQUEST_ERROR = 'CLAIM_REQUEST_ERROR';

export const REMOVE_PAYMENT_REQUESTING = 'REMOVE_PAYMENT_REQUESTING';
export const REMOVE_PAYMENT_SUCCESS = 'REMOVE_PAYMENT_SUCCESS';
export const REMOVE_PAYMENT_ERROR = 'REMOVE_PAYMENT_ERROR';

export const CREATE_PAYMENT_REQUESTING = 'CREATE_PAYMENT_REQUESTING';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_ERROR = 'CREATE_PAYMENT_ERROR';

export const CREATE_NOTE_REQUESTING = 'CREATE_NOTE_REQUESTING';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR';
