export const CLAIMS_REQUESTING = "CLAIMS_REQUESTING";
export const CLAIMS_REQUEST_SUCCESS = "CLAIMS_REQUEST_SUCCESS";
export const CLAIMS_ERROR = "CLAIMS_ERROR";

export const CLAIM_UPDATING = "CLAIM_UPDATING";
export const CLAIM_UPDATE_SUCCESS = "CLAIM_UPDATE_SUCCESS";

export const CLAIM_TYPES = "CLAIM_TYPES";
export const CLAIM_TYPES_SUCCESS = "CLAIM_TYPES_SUCCESS";

export const CLAIM_REQUESTING = "CLAIM_REQUESTING";
export const CLAIM_REQUEST_SUCCESS = "CLAIM_REQUEST_SUCCESS";

export const CREATE_PAYMENT_REQUESTING = "CREATE_PAYMENT_REQUESTING";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";

export const CREATE_NOTE_REQUESTING = "CREATE_NOTE_REQUESTING";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";

export const UPDATE_RESUME_REQUESTING = "UPDATE_RESUME_REQUESTING";
export const UPDATE_RESUME_SUCCESS = "UPDATE_RESUME_SUCCESS";

export const CLAIM_DETAILS_UPDATING = "CLAIM_DETAILS_UPDATING";
export const CLAIM_DETAILS_UPDATE_SUCCESS = "CLAIM_DETAILS_UPDATE_SUCCESS";

export const CLAIMS_BY_MEMBER = "CLAIMS_BY_MEMBER";
export const CLAIMS_BY_MEMBER_SUCCESS = "CLAIMS_BY_MEMBER_SUCCESS";

export const SORT_CLAIMS_LIST = "SORT_CLAIMS_LIST";
