
export const CLEANUP_DASHDBOARD_ITEM = 'CLEANUP_DASHDBOARD_ITEM';
export const DASHBOARD_ERROR_RECEIVED = 'DASHBOARD_ERROR_RECEIVED';
export const DASHBOARD_UPDATED = 'DASHBOARD_UPDATED';
export const UPDATES_REQUEST_SUCCESS = 'UPDATES_REQUEST_SUCCESS';

