export const MEMBER_INS_REQUESTING = 'MEMBER_INS_REQUESTING';
export const MEMBER_INS_SUCCESS = 'MEMBER_INS_SUCCESS';
export const MEMBER_INS_ERROR = 'MEMBER_INS_ERROR';

export const MEMBER_INS_SEARCH_REQUESTING = 'MEMBER_INS_SEARCH_REQUESTING';
export const MEMBER_INS_SEARCH_SUCCESS = 'MEMBER_INS_SEARCH_SUCCESS';

export const SET_MEMBER_INS_FILTER = 'SET_MEMBER_INS_FILTER';
export const SORT_MEMBER_INS_LIST = 'SORT_MEMBER_INS_LIST';
