export const ADD_MESSAGE = "ADD_MESSAGE";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const ERROR_RECEIVED = "ERROR_RECEIVED";
export const CLEAR_MESSAGES_LIST = "CLEAR_MESSAGES_LIST";
export const SET_ACTIVE_CONNECTION = "SET_ACTIVE_CONNECTION";

export const MEMBER_REQUESTING = "MEMBER_REQUESTING";
export const MEMBER_REQUEST_SUCCESS = "MEMBER_REQUEST_SUCCESS";
export const MEMBER_REQUEST_ERROR = "MEMBER_REQUEST_ERROR";

export const MEMBERS_REQUESTING = "MEMBERS_REQUESTING";
export const MEMBERS_REQUEST_SUCCESS = "MEMBERS_REQUEST_SUCCESS";
export const MEMBERS_ERROR = "MEMBERS_ERROR";

export const MEMBER_SEARCH_REQUESTING = "MEMBER_SEARCH_REQUESTING";
export const MEMBERS_SEARCH_SUCCESS = "MEMBERS_SEARCH_SUCCESS";

export const NEW_MESSAGES_RECEIVED = "NEW_MESSAGES_RECEIVED";

export const SET_MEMBER_FILTER = "SET_MEMBER_FILTER";

export const INSURANCE_REQUESTING = "INSURANCE_REQUESTING";
export const INSURANCE_REQUEST_SUCCESS = "INSURANCE_REQUEST_SUCCESS";
export const INSURANCE_ERROR = "INSURANCE_ERROR";

export const INSURANCES_LIST_REQUESTING = "INSURANCES_LIST_REQUESTING";
export const INSURANCES_LIST_REQUEST_SUCCESS =
  "INSURANCES_LIST_REQUEST_SUCCESS";

export const SAVE_INSURANCE_DATE = "SAVE_INSURANCE_DATE";
export const SAVE_ACTIVATION_DATE_SUCCESS = "SAVE_ACTIVATION_DATE_SUCCESS";
export const SAVE_CANCELLATION_DATE_SUCCESS = "SAVE_CANCELLATION_DATE_SUCCESS";

export const SORT_MEMBERS_LIST = "SORT_MEMBERS_LIST";

export const SEND_CANCEL_REQUEST = "SEND_CANCEL_REQUEST";
export const SEND_CANCEL_REQUEST_SUCCESS = "SEND_CANCEL_REQUEST_SUCCESS";

export const SEND_CERTIFICATE = "SEND_CERTIFICATE";
export const SEND_CERTIFICATE_SUCCESS = "SEND_CERTIFICATE_SUCCESS";
export const SEND_CERTIFICATE_ERROR = "SEND_CERTIFICATE_ERROR";

export const MEMBER_COMPANY_STATUS = "MEMBER_COMPANY_STATUS";
export const MEMBER_COMPANY_STATUS_SUCCESS = "MEMBER_COMPANY_STATUS_SUCCESS";
export const MEMBER_COMPANY_STATUS_ERROR = "MEMBER_COMPANY_STATUS_ERROR";

export const EDIT_MEMBER_DETAILS = "EDIT_MEMBER_DETAILS";
export const EDIT_MEMBER_DETAILS_SUCCESS = "EDIT_MEMBER_DETAILS_SUCCESS";

export const MEMBER_CREATE_MODIFIED_INSURANCE =
  "MEMBER_CREATE_MODIFIED_INSURANCE";
export const MEMBER_CREATE_MODIFIED_INSURANCE_SUCCESS =
  "MEMBER_CREATE_MODIFIED_INSURANCE_SUCCESS";

export const MODIFY_INSURANCE = "MODIFY_INSURANCE";
export const MODIFY_INSURANCE_SUCCESS = "MODIFY_INSURANCE_SUCCESS";
