export const QUESTIONS_REQUESTING = 'QUESTIONS_REQUESTING';
export const QUESTIONS_REQUEST_SUCCESS = 'QUESTIONS_REQUEST_SUCCESS';
export const QUESTION_ERROR = 'QUESTION_ERROR';
export const QUESTION_ANSWERING = 'QUESTION_ANSWERING';
export const QUESTION_ANSWER_SUCCESS = 'QUESTION_ANSWER_SUCCESS';
export const ANSWER_ERROR = 'QUESTION_ERROR';
export const QUESTION_DONE_MSG = 'QUESTION_DONE_MSG';
