export const QUESTIONS_REQUESTING = 'QUESTIONS_REQUESTING';
export const QUESTIONS_REQUEST_SUCCESS = 'QUESTIONS_REQUEST_SUCCESS';
export const QUESTIONS_REQUEST_ERROR = 'QUESTIONS_REQUEST_ERROR';
export const QUESTION_ANSWERING = 'QUESTION_ANSWERING';
export const QUESTION_ANSWER_SUCCESS = 'QUESTION_ANSWER_SUCCESS';
